// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces/estimate_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/interfaces/estimate_repository_interface.go -destination=internal/usecase/interfaces/mocks/mock_estimate_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "mecanica_xpto/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIEstimateRepository is a mock of IEstimateRepository interface.
type MockIEstimateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIEstimateRepositoryMockRecorder
	isgomock struct{}
}

// MockIEstimateRepositoryMockRecorder is the mock recorder for MockIEstimateRepository.
type MockIEstimateRepositoryMockRecorder struct {
	mock *MockIEstimateRepository
}

// NewMockIEstimateRepository creates a new mock instance.
func NewMockIEstimateRepository(ctrl *gomock.Controller) *MockIEstimateRepository {
	mock := &MockIEstimateRepository{ctrl: ctrl}
	mock.recorder = &MockIEstimateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEstimateRepository) EXPECT() *MockIEstimateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIEstimateRepository) Create(ctx context.Context, e entities.Estimate) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIEstimateRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIEstimateRepository)(nil).Create), ctx, e)
}

// GetByID mocks base method.
func (m *MockIEstimateRepository) GetByID(ctx context.Context, id string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIEstimateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIEstimateRepository)(nil).GetByID), ctx, id)
}

// GetByOSID mocks base method.
func (m *MockIEstimateRepository) GetByOSID(ctx context.Context, osID string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOSID", ctx, osID)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOSID indicates an expected call of GetByOSID.
func (mr *MockIEstimateRepositoryMockRecorder) GetByOSID(ctx, osID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOSID", reflect.TypeOf((*MockIEstimateRepository)(nil).GetByOSID), ctx, osID)
}

// UpdatePriceByID mocks base method.
func (m *MockIEstimateRepository) UpdatePriceByID(ctx context.Context, id string, newPrice float64) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriceByID", ctx, id, newPrice)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePriceByID indicates an expected call of UpdatePriceByID.
func (mr *MockIEstimateRepositoryMockRecorder) UpdatePriceByID(ctx, id, newPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriceByID", reflect.TypeOf((*MockIEstimateRepository)(nil).UpdatePriceByID), ctx, id, newPrice)
}

// UpdateStatusByOSID mocks base method.
func (m *MockIEstimateRepository) UpdateStatusByOSID(ctx context.Context, osID string, status entities.EstimateStatus) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByOSID", ctx, osID, status)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusByOSID indicates an expected call of UpdateStatusByOSID.
func (mr *MockIEstimateRepositoryMockRecorder) UpdateStatusByOSID(ctx, osID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByOSID", reflect.TypeOf((*MockIEstimateRepository)(nil).UpdateStatusByOSID), ctx, osID, status)
}
