// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces/billing_payment_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/interfaces/billing_payment_repository_interface.go -destination=internal/usecase/interfaces/mocks/mock_billing_payment_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "mecanica_xpto/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIBillingPaymentRepository is a mock of IBillingPaymentRepository interface.
type MockIBillingPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIBillingPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockIBillingPaymentRepositoryMockRecorder is the mock recorder for MockIBillingPaymentRepository.
type MockIBillingPaymentRepositoryMockRecorder struct {
	mock *MockIBillingPaymentRepository
}

// NewMockIBillingPaymentRepository creates a new mock instance.
func NewMockIBillingPaymentRepository(ctrl *gomock.Controller) *MockIBillingPaymentRepository {
	mock := &MockIBillingPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockIBillingPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBillingPaymentRepository) EXPECT() *MockIBillingPaymentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIBillingPaymentRepository) Create(ctx context.Context, p entities.BillingPayment) (entities.BillingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(entities.BillingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIBillingPaymentRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIBillingPaymentRepository)(nil).Create), ctx, p)
}

// GetByID mocks base method.
func (m *MockIBillingPaymentRepository) GetByID(ctx context.Context, id string) (entities.BillingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entities.BillingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIBillingPaymentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIBillingPaymentRepository)(nil).GetByID), ctx, id)
}

// ListByEstimateID mocks base method.
func (m *MockIBillingPaymentRepository) ListByEstimateID(ctx context.Context, estimateID string) ([]entities.BillingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEstimateID", ctx, estimateID)
	ret0, _ := ret[0].([]entities.BillingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEstimateID indicates an expected call of ListByEstimateID.
func (mr *MockIBillingPaymentRepositoryMockRecorder) ListByEstimateID(ctx, estimateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEstimateID", reflect.TypeOf((*MockIBillingPaymentRepository)(nil).ListByEstimateID), ctx, estimateID)
}
