// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces/payment_gateway_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/interfaces/payment_gateway_interface.go -destination=internal/usecase/interfaces/mocks/mock_payment_gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPaymentGateway is a mock of IPaymentGateway interface.
type MockIPaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentGatewayMockRecorder
	isgomock struct{}
}

// MockIPaymentGatewayMockRecorder is the mock recorder for MockIPaymentGateway.
type MockIPaymentGatewayMockRecorder struct {
	mock *MockIPaymentGateway
}

// NewMockIPaymentGateway creates a new mock instance.
func NewMockIPaymentGateway(ctrl *gomock.Controller) *MockIPaymentGateway {
	mock := &MockIPaymentGateway{ctrl: ctrl}
	mock.recorder = &MockIPaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentGateway) EXPECT() *MockIPaymentGatewayMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockIPaymentGateway) CreatePayment(ctx context.Context, requestPayload json.RawMessage) (string, string, json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, requestPayload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(json.RawMessage)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockIPaymentGatewayMockRecorder) CreatePayment(ctx, requestPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockIPaymentGateway)(nil).CreatePayment), ctx, requestPayload)
}
