// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/billing_payment_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/billing_payment_usecase.go -destination=internal/adapter/http/handlers/mocks/mock_billing_payment_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	entities "mecanica_xpto/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIBillingPaymentUseCase is a mock of IBillingPaymentUseCase interface.
type MockIBillingPaymentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIBillingPaymentUseCaseMockRecorder
	isgomock struct{}
}

// MockIBillingPaymentUseCaseMockRecorder is the mock recorder for MockIBillingPaymentUseCase.
type MockIBillingPaymentUseCaseMockRecorder struct {
	mock *MockIBillingPaymentUseCase
}

// NewMockIBillingPaymentUseCase creates a new mock instance.
func NewMockIBillingPaymentUseCase(ctrl *gomock.Controller) *MockIBillingPaymentUseCase {
	mock := &MockIBillingPaymentUseCase{ctrl: ctrl}
	mock.recorder = &MockIBillingPaymentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBillingPaymentUseCase) EXPECT() *MockIBillingPaymentUseCaseMockRecorder {
	return m.recorder
}

// CreateAndApprove mocks base method.
func (m *MockIBillingPaymentUseCase) CreateAndApprove(ctx context.Context, estimateID string, mpPayload json.RawMessage) (entities.BillingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndApprove", ctx, estimateID, mpPayload)
	ret0, _ := ret[0].(entities.BillingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndApprove indicates an expected call of CreateAndApprove.
func (mr *MockIBillingPaymentUseCaseMockRecorder) CreateAndApprove(ctx, estimateID, mpPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndApprove", reflect.TypeOf((*MockIBillingPaymentUseCase)(nil).CreateAndApprove), ctx, estimateID, mpPayload)
}

// GetByID mocks base method.
func (m *MockIBillingPaymentUseCase) GetByID(ctx context.Context, id string) (entities.BillingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entities.BillingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIBillingPaymentUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIBillingPaymentUseCase)(nil).GetByID), ctx, id)
}

// ListByEstimateID mocks base method.
func (m *MockIBillingPaymentUseCase) ListByEstimateID(ctx context.Context, estimateID string) ([]entities.BillingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEstimateID", ctx, estimateID)
	ret0, _ := ret[0].([]entities.BillingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEstimateID indicates an expected call of ListByEstimateID.
func (mr *MockIBillingPaymentUseCaseMockRecorder) ListByEstimateID(ctx, estimateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEstimateID", reflect.TypeOf((*MockIBillingPaymentUseCase)(nil).ListByEstimateID), ctx, estimateID)
}
