// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/estimate_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/estimate_usecase.go -destination=internal/adapter/http/handlers/mocks/mock_estimate_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "mecanica_xpto/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIEstimateUseCase is a mock of IEstimateUseCase interface.
type MockIEstimateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIEstimateUseCaseMockRecorder
	isgomock struct{}
}

// MockIEstimateUseCaseMockRecorder is the mock recorder for MockIEstimateUseCase.
type MockIEstimateUseCaseMockRecorder struct {
	mock *MockIEstimateUseCase
}

// NewMockIEstimateUseCase creates a new mock instance.
func NewMockIEstimateUseCase(ctrl *gomock.Controller) *MockIEstimateUseCase {
	mock := &MockIEstimateUseCase{ctrl: ctrl}
	mock.recorder = &MockIEstimateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEstimateUseCase) EXPECT() *MockIEstimateUseCaseMockRecorder {
	return m.recorder
}

// ApproveByOSID mocks base method.
func (m *MockIEstimateUseCase) ApproveByOSID(ctx context.Context, osID string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveByOSID", ctx, osID)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveByOSID indicates an expected call of ApproveByOSID.
func (mr *MockIEstimateUseCaseMockRecorder) ApproveByOSID(ctx, osID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveByOSID", reflect.TypeOf((*MockIEstimateUseCase)(nil).ApproveByOSID), ctx, osID)
}

// CalculateEstimate mocks base method.
func (m *MockIEstimateUseCase) CalculateEstimate(ctx context.Context, osID string, price float64) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateEstimate", ctx, osID, price)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateEstimate indicates an expected call of CalculateEstimate.
func (mr *MockIEstimateUseCaseMockRecorder) CalculateEstimate(ctx, osID, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateEstimate", reflect.TypeOf((*MockIEstimateUseCase)(nil).CalculateEstimate), ctx, osID, price)
}

// CancelByOSID mocks base method.
func (m *MockIEstimateUseCase) CancelByOSID(ctx context.Context, osID string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelByOSID", ctx, osID)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelByOSID indicates an expected call of CancelByOSID.
func (mr *MockIEstimateUseCaseMockRecorder) CancelByOSID(ctx, osID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelByOSID", reflect.TypeOf((*MockIEstimateUseCase)(nil).CancelByOSID), ctx, osID)
}

// GetByID mocks base method.
func (m *MockIEstimateUseCase) GetByID(ctx context.Context, id string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIEstimateUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIEstimateUseCase)(nil).GetByID), ctx, id)
}

// GetByOSID mocks base method.
func (m *MockIEstimateUseCase) GetByOSID(ctx context.Context, osID string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOSID", ctx, osID)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOSID indicates an expected call of GetByOSID.
func (mr *MockIEstimateUseCaseMockRecorder) GetByOSID(ctx, osID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOSID", reflect.TypeOf((*MockIEstimateUseCase)(nil).GetByOSID), ctx, osID)
}

// RejectByOSID mocks base method.
func (m *MockIEstimateUseCase) RejectByOSID(ctx context.Context, osID string) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectByOSID", ctx, osID)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectByOSID indicates an expected call of RejectByOSID.
func (mr *MockIEstimateUseCaseMockRecorder) RejectByOSID(ctx, osID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectByOSID", reflect.TypeOf((*MockIEstimateUseCase)(nil).RejectByOSID), ctx, osID)
}

// UpdateEstimatePrice mocks base method.
func (m *MockIEstimateUseCase) UpdateEstimatePrice(ctx context.Context, estimateID string, newPrice float64) (entities.Estimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEstimatePrice", ctx, estimateID, newPrice)
	ret0, _ := ret[0].(entities.Estimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEstimatePrice indicates an expected call of UpdateEstimatePrice.
func (mr *MockIEstimateUseCaseMockRecorder) UpdateEstimatePrice(ctx, estimateID, newPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEstimatePrice", reflect.TypeOf((*MockIEstimateUseCase)(nil).UpdateEstimatePrice), ctx, estimateID, newPrice)
}
